import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Gaurav',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Chintu',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      //_id: '1',
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 120,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 20,
      description: 'High quality shirt',
      badge: '15% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Adidas Casual Shirt',
      slug: 'Adidas-casual-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 240,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 8,
      description: 'Stylish and comfortable',
      badge: '12% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Puma Stretch Shirt',
      slug: 'Puma-stretch-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 490,
      countInStock: 10,
      brand: 'Puma',
      rating: 4.6,
      numReviews: 15,
      description: 'Soft stretch cotton shirt',
      badge: '20% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: "Levi's Denim Shirt",
      slug: 'levis-denim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 180,
      countInStock: 0,
      brand: "Levi's",
      rating: 4.4,
      numReviews: 11,
      description: 'Rugged denim for daily wear',
      badge: '19% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'U.S. Polo Classic Shirt',
      slug: 'us-polo-classic-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 210,
      countInStock: 10,
      brand: 'U.S. Polo',
      rating: 4.5,
      numReviews: 14,
      description: 'Classic fit with modern touch',
      badge: '15% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Jack & Jones Linen Shirt',
      slug: 'jack-jones-linen-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 195,
      countInStock: 10,
      brand: 'Jack & Jones',
      rating: 4.2,
      numReviews: 12,
      description: 'Breathable fabric, perfect for summer',
      badge: '17% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Allen Solly Formal Shirt',
      slug: 'allen-solly-formal-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 275,
      countInStock: 10,
      brand: 'Allen Solly',
      rating: 4.3,
      numReviews: 13,
      description: 'Perfect for meetings and formals',
      badge: '27% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Van Heusen Executive Shirt',
      slug: 'van-heusen-executive-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 220,
      countInStock: 10,
      brand: 'Van Heusen',
      rating: 4.5,
      numReviews: 9,
      description: 'Designed for executives',
      badge: '13% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Mufti Printed Shirt',
      slug: 'mufti-printed-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 200,
      countInStock: 10,
      brand: 'Mufti',
      rating: 4.1,
      numReviews: 7,
      description: 'Trendy prints with cool vibe',
      badge: '18% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Reebok Activewear Shirt',
      slug: 'reebok-activewear-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 250,
      countInStock: 20,
      brand: 'Reebok',
      rating: 4.0,
      numReviews: 10,
      description: 'High quality activewear shirt',
      badge: '25% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Nike Slim Fit Pant',
      slug: 'nike-slim-fit-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 999,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'Perfect fit for everyday wear',
      badge: '10% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Adidas Training Pant',
      slug: 'adidas-training-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 1149,
      countInStock: 5,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'Best for gym and training',
      badge: '25% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: 'Puma Jogger Pant',
      slug: 'puma-jogger-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 1249,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 35,
      description: 'Comfortable joggers for casual wear',
      badge: '20% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
    {
      name: "Men's Slim Fit Cotton Shirt",
      slug: 'slim-fit-cotton-shirt',
      category: "Men's Clothing",
      image: '/images/p4.jpg',
      price: 1299,
      countInStock: 18,
      brand: 'Raymond',
      rating: 4.2,
      numReviews: 201,
      description: 'A smart casual shirt ideal for office or evening wear.',
      badge: '40% OFF',
      seller: 'FashionHub',
      delivery: 'Delivery by Wed, Jul 31',
      returnPolicy: '15-day Return Policy',
      highlights: [
        'Slim Fit',
        '100% Pure Cotton',
        'Perfect for Casual & Formal Wear',
      ],
      sizeFit: "Model is 6'0 and is wearing size M",
      specifications: {
        fabric: 'Cotton',
        pattern: 'Solid',
        sleeve: 'Full Sleeve',
        collar: 'Spread Collar',
        fit: 'Slim Fit',
        occasion: 'Casual',
        washCare: 'Machine wash',
      },
    },
  ],
};

export default data;
